import type { Inputs, InputBounds, SalaryPreset } from './types';

export const DEFAULT_INPUTS: Inputs = {
  currentAge: 23,
  startAge: 23,
  retirementAge: 67,
  lifeExpectancy: 83,
  currentSalary: 68870,
  salaryGrowth: 3,
  expectedReturn: 7,
  inflationRate: 2.5,
  enable401k: true,
  enableRoth: false,
  enableHSA: false,
  contribution401k: 10,
  matchPercent: 50,
  matchLimit: 6,
  rothMatch401k: true,
  rothContribution: 7000,
  hsaContribution: 4150,
  contributionTiming: 'start',
  enableStartingBalances: false,
  starting401k: 0,
  startingRoth: 0,
  startingHSA: 0,
};
export const LIMITS = {
  max401kEmployee: 23000,
  max401kTotal: 69000,
  rothAnnual: 7500,
  hsaIndividual: 4150,
  hsaFamily: 8300,
};
export const SIRKISMS = [
  "I am a capitalist. I love money. No shame.",
  "You don't lose the money from the early years. You lose all the money from the later years.",
  "Drive the truck yourself.",
  "How did most American millionaires achieve their wealth? They saved it. That's it.",
  "Dollar sign goes in FRONT!",
  "This is one of the most important things I could possibly pass on to you.",
  "Careers on TV are fake. Fake. Fake.",
  "I'm old-fashioned.",
  "There are stupid questions.",
  "The secret to wealth is… compound interest.",
  "If you don't find a career, a career will find you.",
  "You look like a jackass if you refer to yourself with lowercase i.",
  "C's get degrees.",
  "A W is better than a D. A D is better than an F. But a C is better than all of them.",
  "The cost of waiting is not $8,000. It's half your retirement.",
  "Work until 74, or start now. Your choice.",
  "If you can't pay cash for the car, you can't afford the car.",
  "Professors are human beings. They have sides.",
  "Don't show up late with a Duncan Donuts cup.",
  "Horror stories exist for a reason.",
];
export const SALARY_PRESETS: SalaryPreset[] = [
  { label: 'Computer Science', salary: 81535 },
  { label: 'Engineering', salary: 78731 },
  { label: 'Math and Sciences', salary: 69709 },
  { label: 'Business', salary: 68870 },
  { label: 'Social Sciences', salary: 67316 },
  { label: 'Agriculture/Natural Resources', salary: 63122 },
  { label: 'Communications', salary: 60353 },
  { label: 'Humanities/Liberal Arts', salary: 59410 },
];
export const INPUT_BOUNDS: InputBounds = {
  currentAge: { min: 18, max: 80 },
  startAge: { min: 18, max: 100 },
  retirementAge: { min: 19, max: 100 },
  lifeExpectancy: { min: 40, max: 120 },
  currentSalary: { min: 0, max: 1000000 },
  salaryGrowth: { min: 0, max: 10 },
  expectedReturn: { min: 0, max: 15 },
  inflationRate: { min: 0, max: 10 },
  contribution401k: { min: 0, max: 100 },
  matchPercent: { min: 0, max: 100 },
  matchLimit: { min: 0, max: 100 },
  rothContribution: { min: 0, max: LIMITS.rothAnnual },
  hsaContribution: { min: 0, max: LIMITS.hsaFamily },
  starting401k: { min: 0, max: 10_000_000 },
  startingRoth: { min: 0, max: 10_000_000 },
  startingHSA: { min: 0, max: 10_000_000 },
};
